name: CI to Docker

on:
  push:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      - '**.sh'
      - 'Dockerfile'
      - '.github/workflows/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/towaywei/postgres-with-partman:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
